version: 2
jobs:
    build:
        working_directory: /go/src/github.com/ieee0824/circleci-demo
        docker:
            - image: golang:latest
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: check docker version
                command: |
                    docker version
